spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.yourpackage.ImageEvent
        spring.json.trusted.packages: "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /db
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379

token:
  signing:
    key: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb

logging:
  file:
    name: logging.txt
  level:
    root: INFO
    org.springframework: INFO
    com.example.market: DEBUG

resilience4j:
  circuit breaker:
    instances:
      imageService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
service:
  image:
    upload:
      url: http://localhost:8081/api/images/upload