apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarket
  template:
    metadata:
      labels:
        app: bookmarket
    spec:
      containers:
        - name: bookmarket
          image: bookmarket:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarket-service
spec:
  selector:
    app: bookmarket
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
