apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarket
  template:
    metadata:
      labels:
        app: bookmarket
    spec:
      containers:
        - name: bookmarket
          image: bookmarket:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres"
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"